# Generated by Django 2.2 on 2019-05-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codPais', models.IntegerField(verbose_name='Código')),
                ('pais', models.CharField(max_length=200, verbose_name='País')),
            ],
        ),
    ]
