# Generated by Django 2.2 on 2019-05-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='codPais',
            field=models.IntegerField(verbose_name='Código'),
        ),
    ]
