# Generated by Django 2.2 on 2019-05-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_auto_20190506_1410'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
