# Generated by Django 2.2 on 2019-05-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pais', '0002_auto_20190528_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Descrição'),
        ),
    ]
