# Generated by Django 2.2 on 2019-06-03 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bairro', '0002_bairro_cidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bairro',
            old_name='bairro',
            new_name='nome',
        ),
    ]
