# Generated by Django 2.2 on 2019-06-06 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logradouro', '0002_auto_20190605_1634'),
        ('cidade', '0003_auto_20190530_1530'),
        ('estado', '0003_auto_20190528_1112'),
        ('bairro', '0003_auto_20190603_1434'),
        ('pais', '0003_auto_20190528_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='numero')),
                ('cep', models.CharField(max_length=10, verbose_name='cep')),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bairro.Bairro', verbose_name='bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade.Cidade', verbose_name='cidade')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='estado.Estado', verbose_name='estado')),
                ('logradouro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='logradouro.Logradouro', verbose_name='logradouro')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pais.Pais', verbose_name='estado')),
            ],
        ),
    ]
