# Generated by Django 2.2 on 2019-05-15 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_auto_20190502_1646'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Endereco',
        ),
    ]
