# Generated by Django 2.2 on 2019-05-16 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pais', '0004_pais'),
        ('endereco', '0003_delete_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(verbose_name='Número')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pais.Pais')),
            ],
        ),
    ]
