# Generated by Django 2.2 on 2019-05-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cep', '0001_initial'),
        ('bairro', '0002_bairro_cidade'),
        ('cidade', '0001_initial'),
        ('endereco', '0004_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='endereco',
            name='bairro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bairro.Bairro', verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cep',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cep.Cep', verbose_name='cep'),
        ),
        migrations.AddField(
            model_name='endereco',
            name='cidade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cidade.Cidade', verbose_name='cidade'),
        ),
    ]
