# Generated by Django 2.2 on 2019-05-28 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estado', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='estado',
            new_name='nome',
        ),
    ]
