# Generated by Django 2.2 on 2019-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cadastro', models.CharField(choices=[('forn', 'Fornecedor'), ('clie', 'Cliente'), ('terc', 'Terceirizado'), ('func', 'Funcionário')], max_length=4, verbose_name='Tipo de Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo?')),
                ('nome_fantasia', models.CharField(max_length=200, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=200, verbose_name='CNPJ')),
                ('inscEstadual', models.IntegerField(max_length=15, verbose_name='Insc. Estadual')),
                ('produto', models.CharField(max_length=200, verbose_name='Produto')),
                ('servico', models.CharField(max_length=200, verbose_name='Serviço')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
