# Generated by Django 2.2 on 2019-05-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoajuridica', '0002_auto_20190502_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoajuridica',
            old_name='nome_fantasia',
            new_name='nomeFantasia',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pessoajuridica',
            name='tipo_cadastro',
        ),
    ]
