# Generated by Django 2.2 on 2019-05-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('endereco', '0005_auto_20190516_1545'),
        ('pessoa', '0002_delete_pessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoCadastro', models.CharField(choices=[('forn', 'Fornecedor'), ('clie', 'Cliente'), ('terc', 'Terceirizado'), ('func', 'Funcionário')], max_length=4, verbose_name='Tipo de Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo?')),
                ('endereco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='endereco.Endereco', verbose_name='Endereço')),
            ],
        ),
    ]
