# Generated by Django 2.2 on 2019-05-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoafisica', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='matricula',
            field=models.IntegerField(verbose_name='Matrícula'),
        ),
    ]
