# Generated by Django 2.2 on 2019-05-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoafisica', '0002_auto_20190502_1646'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='dt_nasc',
            new_name='dtNasc',
        ),
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='nome_mae',
            new_name='nomeMae',
        ),
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='nome_pai',
            new_name='nomePai',
        ),
        migrations.RenameField(
            model_name='pessoafisica',
            old_name='resp_financ',
            new_name='respFinanc',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='celular',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='pessoafisica',
            name='tipo_cadastro',
        ),
    ]
