# Generated by Django 2.2 on 2019-05-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoa', '0003_pessoa'),
        ('pessoafisica', '0003_auto_20190516_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoafisica',
            name='id',
        ),
        migrations.AddField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.OneToOneField(default='DEFAULT VALUE', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.Pessoa', verbose_name='Pessoa'),
        ),
    ]
