# Generated by Django 2.2 on 2019-05-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pessoafisica', '0004_auto_20190516_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoafisica',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pessoa.Pessoa', verbose_name='Pessoa'),
        ),
    ]
