# Generated by Django 2.2 on 2019-05-30 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cidade', '0002_cidade_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='cidade',
            new_name='nome',
        ),
    ]
