# Generated by Django 2.2 on 2019-05-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pessoa_fisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cadastro', models.CharField(choices=[('forn', 'Fornecedor'), ('clie', 'Cliente'), ('terc', 'Terceirizado'), ('func', 'Funcionário')], max_length=4, verbose_name='Tipo de Cadastro')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('celular', models.CharField(max_length=15, verbose_name='Celular')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('ativo', models.BooleanField(blank=True, verbose_name='Ativo?')),
                ('cpf', models.CharField(max_length=15, verbose_name='CPF')),
                ('rg', models.CharField(max_length=15, verbose_name='RG')),
                ('dt_nasc', models.DateField(auto_now_add=True, verbose_name='Data de nascimento')),
                ('nome_pai', models.CharField(max_length=200, verbose_name='Nome do pai')),
                ('nome_mae', models.CharField(max_length=200, verbose_name='Nome da mãe')),
                ('resp_financ', models.CharField(max_length=200, verbose_name='Responsável Financeiro')),
                ('matricula', models.IntegerField(max_length=30, verbose_name='Matrícula')),
                ('salario', models.CharField(max_length=100, verbose_name='Salário')),
                ('comissao', models.CharField(max_length=100, verbose_name='Comissão')),
                ('contratado', models.CharField(max_length=100, verbose_name='Contratado')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
