# Generated by Django 2.2 on 2019-05-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bairro', '0001_initial'),
        ('tipo_logradouro', '0001_initial'),
        ('nome_logradouro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logradouro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bairro.Bairro', verbose_name='Tipo de logradouro')),
                ('nomeLogradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nome_logradouro.NomeLogradouro', verbose_name='Nome do logradouro')),
                ('tipoLogradouro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_logradouro.TipoLogradouro', verbose_name='Tipo de logradouro')),
            ],
        ),
    ]
