# Generated by Django 2.2 on 2019-06-05 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nome_logradouro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomelogradouro',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do logradouro'),
        ),
    ]
